### ISSUE TITLE
ImageSharp support

### ISSUE THREAD

**Issue by developervariety** [pgrho/phash#22]

**Comment by pgrho** [comment]
I won't implement it because the ImageSharp isn't standard library and I have never use it. But p-r is welcomed.

FYI: You can make `ImageSharp` binding with essentialy one method to instantiate `ByteImage`. The [WPF binding](https://github.com/pgrho/phash/tree/2e72ff459255390b03e0e0b4f1f6068374659f4e/src/Shipwreck.Phash.PresentationCore) has only 73 lines.
